logging:
    level:
        com:
             towery:
                  ignite: DEBUG
spring:
    application:
        name: data-node-server
    profiles:
        active: dev
    datasource:
        name: my-ignite-web
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/my_ignite_web
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        filters: stat,wall,log4j
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
mybatis:
     mapper-locations: mybatis/**/*.xml
     typeAliasesPackage: com.towery.ignite.mybatis