server:
    port: 18080
    context-path: /web-console
    tomcat:
         uri-encoding: UTF-8
         max-threads: 150
logging:
    level:
        com:
             towery:
                  myignite: DEBUG
spring:
    application:
        name: my-ignite-web-console
    profiles:
        active: dev
    datasource:
        name: my-ignite-web
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/my_ignite_web
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        filters: stat,wall,log4j
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
    mvc:
        view:
            prefix: /jsp/
            suffix: .jsp